[package]
name = "mmc9"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
egui = "0.29.1"
env_logger = "0.11.5"
git2 = "0.19.0"
reqwest = {version="0.12.9", features = ["json", "stream"]  }
serde_json = "1.0.133"
tokio = {version="1.41.1",features = ["full"] }
